name = "caveful_games/rng"
version = "0.1.0"
description = "Useful random-related utilities for Luau"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/luau-rng"
license = "MIT"
includes = ["src/**", "LICENSE", "pesde.toml", "README.md"]
private = true

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.28" }
luau_check = { name = "jiwonz/luau_check", version = "^0.3.11" }
darklua = { name = "pesde/darklua", version = "^0.16.0" }
